name: Build and Publish Development Docker Images

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-dev-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository once
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Testing steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Types Package
        run: |
          cd types
          yarn build
          
      - name: Setup Yarn Workspace Links
        run: |
          yarn install --force
          
      - name: Run Tests
        run: |
          cd app
          yarn test

      # --- Docker build and publish steps ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate a unique tag based on git branch/SHA for dev builds
      - name: Generate Docker Tags
        id: docker_tags
        run: |
          # For pull requests
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAGS=dastro/dastro-fullstack-dev:pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          # For pushes to dev branch
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            echo "TAGS=dastro/dastro-fullstack-dev:dev-${SHORT_SHA},dastro/dastro-fullstack-dev:dev-latest" >> $GITHUB_ENV
          # For manual workflow runs
          else
            echo "TAGS=dastro/dastro-fullstack-dev:dev-manual-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha,scope=fullstack-dev-cache
          cache-to: type=gha,mode=max,scope=fullstack-dev-cache
          tags: ${{ env.TAGS }}
          # For pull requests, only build don't push
          outputs: ${{ github.event_name == 'pull_request' && 'type=docker,dest=/tmp/dev-image.tar' || '' }}
          
      # Output a summary of the image that would have been built (for PRs)
      - name: Output Build Summary for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "### Development Docker Image Built Successfully :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          echo "Image would be tagged as: ${{ env.TAGS }}" >> $GITHUB_STEP_SUMMARY
          echo "Image was built but not pushed (PR build)" >> $GITHUB_STEP_SUMMARY
