name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Custom tag for the Docker image'
        required: false
        default: 'manual'

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository once
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Testing steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Types Package
        run: |
          cd types
          yarn build
          
      - name: Setup Yarn Workspace Links
        run: |
          yarn install --force
          
      - name: Run Tests
        run: |
          cd app
          yarn test

      # --- Docker build and publish steps ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate tag for manual builds
      - name: Generate Docker Tags
        id: docker_tags
        run: |
          CUSTOM_TAG="${{ github.event.inputs.tag }}"
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          
          if [ "$CUSTOM_TAG" != "manual" ]; then
            # User provided a custom tag
            echo "TAGS=dastro/dastro-fullstack:${CUSTOM_TAG}" >> $GITHUB_ENV
            echo "VERSION=${CUSTOM_TAG}" >> $GITHUB_ENV
          else
            # Default manual tag with timestamp
            echo "TAGS=dastro/dastro-fullstack:manual-${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_ENV
            echo "VERSION=manual-${TIMESTAMP}" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=fullstack-manual-cache
          cache-to: type=gha,mode=max,scope=fullstack-manual-cache
          tags: ${{ env.TAGS }}
          build-args: |
            VERSION=${{ env.VERSION }}