name: Test, Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository once
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Testing steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Build Types Package
        run: |
          cd types
          yarn build

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Tests
        run: |
          cd app
          yarn test

      # --- Docker build and publish steps ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          # Use GitHub Actions cache for build layers and adjust the key/scope if desired
          cache-from: type=gha,scope=fullstack-cache
          cache-to: type=gha,mode=max,scope=fullstack-cache
          tags: |
            dastro/dastro-fullstack-dev:latest
            dastro/dastro-fullstack-dev:0.0.1