name: Build and Publish Production Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository once
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Testing steps ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Types Package
        run: |
          cd types
          yarn build
          
      - name: Setup Yarn Workspace Links
        run: |
          yarn install --force
          
      - name: Run Tests
        run: |
          cd app
          yarn test

      # --- Docker build and publish steps ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Generate production tags with versions
      - name: Generate Docker Tags
        id: docker_tags
        run: |
          # Get package.json version or default to 0.0.1
          if [ -f "package.json" ]; then
            VERSION=$(node -p "require('./package.json').version || '0.0.1'")
          else
            VERSION="0.0.1"
          fi
          
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          
          # For main branch pushes - tag with version, latest, and commit SHA
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TAGS=dastro/dastro-fullstack:${VERSION},dastro/dastro-fullstack:latest,dastro/dastro-fullstack:${SHORT_SHA}" >> $GITHUB_ENV
          # For manual workflow runs
          else
            echo "TAGS=dastro/dastro-fullstack:manual-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=fullstack-prod-cache
          cache-to: type=gha,mode=max,scope=fullstack-prod-cache
          tags: ${{ env.TAGS }}