name: Nightly Docker Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-nightly:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install Node 22 and enable Yarn caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn

      # 3) Install dependencies (immutable = locked versions, no updates)
      - name: Install Dependencies
        run: |
          yarn install --immutable

      # 4) Build all packages (topological if your scripts call 'yarn workspaces foreach')
      - name: Build Monorepo
        run: |
          yarn build

      # 5) Run Tests
      - name: Run Tests
        run: |
          yarn test

      # 6) Docker build & push steps
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate nightly tag
        run: |
          NIGHTLY_DATE=$(date +'%Y%m%d')
          echo "TAGS=dastro/fullstack-pb-template:nightly-${NIGHTLY_DATE},dastro/fullstack-pb-template:nightly" >> $GITHUB_ENV
          echo "VERSION=nightly-${NIGHTLY_DATE}" >> $GITHUB_ENV

      # 7) Build & push the Docker image with GHA caching for layers
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=fullstack-nightly-cache
          cache-to: type=gha,mode=max,scope=fullstack-nightly-cache
          tags: ${{ env.TAGS }}
          build-args: |
            VERSION=${{ env.VERSION }}
