name: Nightly Docker Build

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup and testing
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build Types Package
        run: |
          cd types
          yarn build
          
      - name: Setup Yarn Workspace Links
        run: |
          yarn install --force
          
      - name: Run Tests
        run: |
          cd app
          yarn test

      # Docker build and publish
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate nightly tag
        run: |
          NIGHTLY_DATE=$(date +'%Y%m%d')
          NIGHTLY_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "TAGS=dastro/dastro-fullstack:nightly-${NIGHTLY_DATE},dastro/dastro-fullstack:nightly-${NIGHTLY_DATE}-${NIGHTLY_SHA},dastro/dastro-fullstack:nightly" >> $GITHUB_ENV
          echo "VERSION=nightly-${NIGHTLY_DATE}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha,scope=fullstack-nightly-cache
          cache-to: type=gha,mode=max,scope=fullstack-nightly-cache
          tags: ${{ env.TAGS }}
          build-args: |
            VERSION=${{ env.VERSION }} 