name: PR Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install Node 22 and enable Yarn caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn

      # 3) Install dependencies (immutable = locked versions, no updates)
      - name: Install Dependencies
        run: |
          yarn install --immutable

      # 4) Build all packages (topological if your scripts call 'yarn workspaces foreach')
      - name: Build Monorepo
        run: |
          yarn build

      # 5) Run Tests
      - name: Run Tests
        run: |
          yarn test